2020-07-09 00:00:12.906 [error] <0.1115.0> CRASH REPORT Process <0.1115.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:00:12.907 [error] <0.1115.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1113.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:00:38.855 [error] <0.1154.0> CRASH REPORT Process <0.1154.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:00:38.856 [error] <0.1154.0> Cowboy stream 7 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1113.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:01:17.206 [error] <0.1197.0> CRASH REPORT Process <0.1197.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:01:17.209 [error] <0.1197.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1195.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:01:34.716 [error] <0.1268.0> CRASH REPORT Process <0.1268.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:01:34.717 [error] <0.1268.0> Cowboy stream 13 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1195.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:02:21.290 [error] <0.1282.0> CRASH REPORT Process <0.1282.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:02:21.291 [error] <0.1282.0> Cowboy stream 15 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1195.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:02:59.903 [error] <0.1322.0> CRASH REPORT Process <0.1322.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:02:59.904 [error] <0.1322.0> Cowboy stream 16 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1195.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:04:37.796 [error] <0.1390.0> CRASH REPORT Process <0.1390.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:04:37.797 [error] <0.1390.0> Cowboy stream 6 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1364.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:05:11.090 [error] <0.1404.0> CRASH REPORT Process <0.1404.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:05:11.091 [error] <0.1404.0> Cowboy stream 8 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1364.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:05:25.327 [error] <0.1445.0> CRASH REPORT Process <0.1445.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:05:25.329 [error] <0.1445.0> Cowboy stream 10 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1364.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:07:11.630 [error] <0.1460.0> CRASH REPORT Process <0.1460.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:07:11.632 [error] <0.1460.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1458.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:07:28.854 [error] <0.1488.0> CRASH REPORT Process <0.1488.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:07:28.855 [error] <0.1488.0> Cowboy stream 7 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1458.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:07:38.029 [error] <0.1518.0> CRASH REPORT Process <0.1518.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:07:38.030 [error] <0.1518.0> Cowboy stream 3 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1459.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:07:40.530 [error] <0.1553.0> CRASH REPORT Process <0.1553.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:07:40.531 [error] <0.1553.0> Cowboy stream 7 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1459.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:08:14.265 [error] <0.1613.0> CRASH REPORT Process <0.1613.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:08:14.270 [error] <0.1613.0> Cowboy stream 10 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1459.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:08:27.446 [error] <0.1627.0> CRASH REPORT Process <0.1627.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:08:27.447 [error] <0.1627.0> Cowboy stream 13 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1459.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:08:31.018 [error] <0.1667.0> CRASH REPORT Process <0.1667.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:08:31.019 [error] <0.1667.0> Cowboy stream 15 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1459.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:09:37.354 [error] <0.1728.0> CRASH REPORT Process <0.1728.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:09:37.355 [error] <0.1728.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1726.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:11:29.049 [error] <0.1852.0> CRASH REPORT Process <0.1852.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:11:29.050 [error] <0.1852.0> Cowboy stream 15 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1744.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9,pt-PT...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:11:42.305 [error] <0.1859.0> CRASH REPORT Process <0.1859.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:11:42.309 [error] <0.1859.0> Cowboy stream 16 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1744.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.AdminLive',reason => nil},[{'Elixir.AdminLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/co..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:12:01.636 [error] <0.1871.0> CRASH REPORT Process <0.1871.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.PageLive',reason => nil},[{'Elixir.PageLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/cont..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:12:01.637 [error] <0.1871.0> Cowboy stream 18 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1744.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.PageLive',reason => nil},[{'Elixir.PageLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/cont..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:12:10.203 [error] <0.1934.0> CRASH REPORT Process <0.1934.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.PageLive',reason => nil},[{'Elixir.PageLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/cont..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:12:10.204 [error] <0.1934.0> Cowboy stream 21 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1744.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.PageLive',reason => nil},[{'Elixir.PageLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/cont..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:12:20.921 [error] <0.1949.0> CRASH REPORT Process <0.1949.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.PageLive',reason => nil},[{'Elixir.PageLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/cont..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:12:20.921 [error] <0.1949.0> Cowboy stream 24 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1744.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.PageLive',reason => nil},[{'Elixir.PageLive','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,289}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,104}]},{'Elixir.Phoenix.LiveView.Controller',live_render,3,[{file,"lib/phoenix_live_view/cont..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:13:08.605 [error] <0.2062.0> CRASH REPORT Process <0.2062.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => list_users,message => nil,module => 'Elixir.FidelityApp.Accounts',reason => nil},[{'Elixir.FidelityApp.Accounts',list_users,[],[]},{'Elixir.FidelityAppWeb.AdminLive',fetch,1,[{file,"lib/fidelity_app_web/live/admin_live.ex"},{line,16}]},{'Elixir.FidelityAppWeb.AdminLive',mount,3,[{file,"lib/fidelity_app_web/live/admin_live.ex"},{line,9}]},{'Elixir.Phoenix.LiveView.Utils','-maybe_call_live_view_mount!/4-fun-0-',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:13:08.606 [error] <0.2062.0> Cowboy stream 32 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1744.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => list_users,message => nil,module => 'Elixir.FidelityApp.Accounts',reason => nil},[{'Elixir.FidelityApp.Accounts',list_users,[],[]},{'Elixir.FidelityAppWeb.AdminLive',fetch,1,[{file,"lib/fidelity_app_web/live/admin_live.ex"},{line,16}]},{'Elixir.FidelityAppWeb.AdminLive',mount,3,[{file,"lib/fidelity_app_web/live/admin_live.ex"},{line,9}]},{'Elixir.Phoenix.LiveView.Utils','-maybe_call_live_view_mount!/4-fun-0-',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:14:31.292 [error] <0.2131.0> CRASH REPORT Process <0.2131.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:14:31.293 [error] <0.2131.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2129.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:17:42.634 [error] <0.2152.0> CRASH REPORT Process <0.2152.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:17:42.635 [error] <0.2152.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2150.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:18:30.873 [error] <0.2193.0> CRASH REPORT Process <0.2193.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:18:30.874 [error] <0.2193.0> Cowboy stream 2 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2151.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:18:38.688 [error] <0.2243.0> CRASH REPORT Process <0.2243.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:18:38.691 [error] <0.2243.0> Cowboy stream 7 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2192.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:19:16.482 [error] <0.2259.0> CRASH REPORT Process <0.2259.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:19:16.482 [error] <0.2259.0> Cowboy stream 3 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2151.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:19:33.008 [error] <0.2296.0> CRASH REPORT Process <0.2296.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:19:33.012 [error] <0.2296.0> Cowboy stream 9 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2151.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:20:24.116 [error] <0.2311.0> CRASH REPORT Process <0.2311.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.AdminView',reason => nil},[{'Elixir.AdminView',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminLive',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminLive',...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:20:24.117 [error] <0.2311.0> Cowboy stream 12 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2151.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.AdminView',reason => nil},[{'Elixir.AdminView',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminLive',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminLive',...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:20:50.521 [error] <0.2348.0> CRASH REPORT Process <0.2348.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.AdminView',reason => nil},[{'Elixir.AdminView',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminLive',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminLive',...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:20:50.525 [error] <0.2348.0> Cowboy stream 19 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2151.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.AdminView',reason => nil},[{'Elixir.AdminView',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminLive',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminLive',...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:21:23.929 [error] <0.2364.0> CRASH REPORT Process <0.2364.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.AdminView',reason => nil},[{'Elixir.AdminView',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminLive',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminLive',...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:21:23.930 [error] <0.2364.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2362.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.AdminView',reason => nil},[{'Elixir.AdminView',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminLive',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminLive',...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:21:30.147 [error] <0.2414.0> CRASH REPORT Process <0.2414.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.AdminView',reason => nil},[{'Elixir.AdminView',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminLive',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminLive',...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:21:30.148 [error] <0.2414.0> Cowboy stream 5 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2362.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.AdminView',reason => nil},[{'Elixir.AdminView',render,[<<"index.html">>,#{'__changed__' => #{users => true},flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminLive',socket => #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__assigns__' => #{flash => #{},live_action => nil,live_module => 'Elixir.FidelityAppWeb.AdminLive',...},...},...},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:22:37.435 [error] <0.2431.0> CRASH REPORT Process <0.2431.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:22:37.439 [error] <0.2431.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2429.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:22:44.209 [error] <0.2467.0> CRASH REPORT Process <0.2467.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:22:44.213 [error] <0.2467.0> Cowboy stream 7 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2429.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:25:16.655 [error] <0.2533.0> CRASH REPORT Process <0.2533.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:25:16.656 [error] <0.2533.0> Cowboy stream 4 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2507.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:26:32.085 [error] <0.2573.0> CRASH REPORT Process <0.2573.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 00:26:32.086 [error] <0.2573.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2571.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 08:33:36.938 [info] <0.43.0> Application lager started on node nonode@nohost
2020-07-09 08:33:36.952 [info] <0.43.0> Application gen_stage started on node nonode@nohost
2020-07-09 08:33:36.956 [info] <0.43.0> Application broadway started on node nonode@nohost
2020-07-09 08:33:36.971 [info] <0.43.0> Application xmerl started on node nonode@nohost
2020-07-09 08:33:37.001 [info] <0.43.0> Application sasl started on node nonode@nohost
2020-07-09 08:33:37.011 [info] <0.43.0> Application tools started on node nonode@nohost
2020-07-09 08:33:37.016 [info] <0.43.0> Application jsx started on node nonode@nohost
2020-07-09 08:33:37.023 [info] <0.43.0> Application recon started on node nonode@nohost
2020-07-09 08:33:37.058 [info] <0.43.0> Application credentials_obfuscation started on node nonode@nohost
2020-07-09 08:33:37.058 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2020-07-09 08:33:37.073 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2020-07-09 08:33:37.081 [info] <0.43.0> Application amqp started on node nonode@nohost
2020-07-09 08:33:37.081 [info] <0.43.0> Application broadway_rabbitmq started on node nonode@nohost
2020-07-09 08:33:37.152 [info] <0.43.0> Application fidelity_rule_engine started on node nonode@nohost
2020-07-09 08:33:37.177 [info] <0.43.0> Application absinthe started on node nonode@nohost
2020-07-09 08:33:37.187 [info] <0.43.0> Application poison started on node nonode@nohost
2020-07-09 08:33:37.195 [info] <0.43.0> Application argon2_elixir started on node nonode@nohost
2020-07-09 08:33:37.203 [info] <0.43.0> Application absinthe_ecto started on node nonode@nohost
2020-07-09 08:33:37.213 [info] <0.43.0> Application absinthe_error_payload started on node nonode@nohost
2020-07-09 08:33:37.216 [info] <0.43.0> Application absinthe_plug started on node nonode@nohost
2020-07-09 08:33:37.418 [info] <0.43.0> Application jose started on node nonode@nohost
2020-07-09 08:33:37.418 [info] <0.43.0> Application guardian started on node nonode@nohost
2020-07-09 08:33:37.420 [info] <0.43.0> Application guardian_db started on node nonode@nohost
2020-07-09 08:33:37.423 [info] <0.43.0> Application basic_auth started on node nonode@nohost
2020-07-09 08:33:37.430 [info] <0.43.0> Application pow started on node nonode@nohost
2020-07-09 08:33:37.705 [info] <0.43.0> Application mnesia started on node nonode@nohost
2020-07-09 08:33:37.720 [info] <0.43.0> Application gqlgateway started on node nonode@nohost
2020-07-09 08:33:42.502 [error] <0.1083.0> CRASH REPORT Process <0.1083.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminuserLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 08:33:42.510 [error] <0.1083.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1081.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminuserLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 08:33:45.207 [error] <0.1114.0> CRASH REPORT Process <0.1114.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminuserLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 08:33:45.208 [error] <0.1114.0> Cowboy stream 9 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1081.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminuserLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 08:33:54.649 [error] <0.1160.0> CRASH REPORT Process <0.1160.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminuserLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 08:33:54.650 [error] <0.1160.0> Cowboy stream 11 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1129.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminuserLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 08:35:57.911 [error] <0.1178.0> CRASH REPORT Process <0.1178.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminuserLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 08:35:57.912 [error] <0.1178.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1177.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminuserLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 08:36:14.161 [error] <0.1216.0> CRASH REPORT Process <0.1216.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @users not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 08:36:14.162 [error] <0.1216.0> Cowboy stream 3 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1177.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @users not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 08:36:31.432 [error] <0.1273.0> CRASH REPORT Process <0.1273.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @users not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 08:36:31.436 [error] <0.1273.0> Cowboy stream 13 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1177.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @users not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 08:36:39.036 [error] <0.1310.0> CRASH REPORT Process <0.1310.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @users not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 08:36:39.036 [error] <0.1310.0> Cowboy stream 20 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1177.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @users not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 08:37:28.206 [error] <0.1346.0> CRASH REPORT Process <0.1346.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @users not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 08:37:28.207 [error] <0.1346.0> Cowboy stream 8 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1215.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @users not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:__changed__, :flash, :live_action, :live_module, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,867}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 08:39:45.024 [error] <0.1474.0> CRASH REPORT Process <0.1474.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminuserLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 08:39:45.024 [error] <0.1474.0> Cowboy stream 11 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1426.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminuserLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 08:53:16.406 [error] <0.1791.0> CRASH REPORT Process <0.1791.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminuserLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 08:53:16.407 [error] <0.1791.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.1789.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action AdminUserLive.Show for FidelityAppWeb.Router.Helpers.live_path/3. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])\n    live_path(conn_or_endpoint, FidelityAppWeb.AdminuserLive, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,374}]},{'Elixir.FidelityAppWeb.AdminuserLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 09:07:00.205 [error] <0.2060.0> CRASH REPORT Process <0.2060.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"lists in Phoenix.HTML and templates may only contain integers representing bytes, binaries or other lists, got invalid entry: #FidelityApp.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, \"users\">, confirmed_at: nil, email: \"admin@test.com\", hashed_password: \"$2b$12$YJ5jWtHjrbbAL3iqvZmgmOEWU7bgk83qiOWjVMIOPNZKOxRbfMfWi\", id: 1, inserted_at: ~N[2020-07-08 22:17:05], role: \"admin\", updated_at: ~N[2020-07-08...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 09:07:00.206 [error] <0.2060.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2059.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"lists in Phoenix.HTML and templates may only contain integers representing bytes, binaries or other lists, got invalid entry: #FidelityApp.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, \"users\">, confirmed_at: nil, email: \"admin@test.com\", hashed_password: \"$2b$12$YJ5jWtHjrbbAL3iqvZmgmOEWU7bgk83qiOWjVMIOPNZKOxRbfMfWi\", id: 1, inserted_at: ~N[2020-07-08 22:17:05], role: \"admin\", updated_at: ~N[2020-07-08...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 09:07:11.249 [error] <0.2096.0> CRASH REPORT Process <0.2096.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"lists in Phoenix.HTML and templates may only contain integers representing bytes, binaries or other lists, got invalid entry: #FidelityApp.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, \"users\">, confirmed_at: nil, email: \"admin@test.com\", hashed_password: \"$2b$12$YJ5jWtHjrbbAL3iqvZmgmOEWU7bgk83qiOWjVMIOPNZKOxRbfMfWi\", id: 1, inserted_at: ~N[2020-07-08 22:17:05], role: \"admin\", updated_at: ~N[2020-07-08...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 09:07:11.250 [error] <0.2096.0> Cowboy stream 5 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2059.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"lists in Phoenix.HTML and templates may only contain integers representing bytes, binaries or other lists, got invalid entry: #FidelityApp.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, \"users\">, confirmed_at: nil, email: \"admin@test.com\", hashed_password: \"$2b$12$YJ5jWtHjrbbAL3iqvZmgmOEWU7bgk83qiOWjVMIOPNZKOxRbfMfWi\", id: 1, inserted_at: ~N[2020-07-08 22:17:05], role: \"admin\", updated_at: ~N[2020-07-08...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 09:09:45.555 [error] <0.2140.0> CRASH REPORT Process <0.2140.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"lists in Phoenix.HTML and templates may only contain integers representing bytes, binaries or other lists, got invalid entry: #FidelityApp.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, \"users\">, confirmed_at: nil, email: \"admin@test.com\", hashed_password: \"$2b$12$YJ5jWtHjrbbAL3iqvZmgmOEWU7bgk83qiOWjVMIOPNZKOxRbfMfWi\", id: 1, inserted_at: ~N[2020-07-08 22:17:05], role: \"admin\", updated_at: ~N[2020-07-08...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 09:09:45.570 [error] <0.2140.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2138.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"lists in Phoenix.HTML and templates may only contain integers representing bytes, binaries or other lists, got invalid entry: #FidelityApp.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, \"users\">, confirmed_at: nil, email: \"admin@test.com\", hashed_password: \"$2b$12$YJ5jWtHjrbbAL3iqvZmgmOEWU7bgk83qiOWjVMIOPNZKOxRbfMfWi\", id: 1, inserted_at: ~N[2020-07-08 22:17:05], role: \"admin\", updated_at: ~N[2020-07-08...">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 09:14:09.297 [error] <0.2229.0> CRASH REPORT Process <0.2229.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"render/1 was not implemented for FidelityAppWeb.AdminuserLive.\n\nMake sure to either explicitly define a render/1 clause with a LiveView template:\n\n    def render(assigns) do\n      ~L\"\"\"\n      ...\n      \"\"\"\n    end\n\nOr create a file at \"/home/sblabreu/projects/fidelity/fidelity/apps/fidelity_app/lib/fidelity_app_web/live/adminuser_live.html.leex\" with the LiveView template.\n">>},[{'Elixir.FidelityAppWeb.AdminuserLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 09:14:09.297 [error] <0.2229.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2228.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"render/1 was not implemented for FidelityAppWeb.AdminuserLive.\n\nMake sure to either explicitly define a render/1 clause with a LiveView template:\n\n    def render(assigns) do\n      ~L\"\"\"\n      ...\n      \"\"\"\n    end\n\nOr create a file at \"/home/sblabreu/projects/fidelity/fidelity/apps/fidelity_app/lib/fidelity_app_web/live/adminuser_live.html.leex\" with the LiveView template.\n">>},[{'Elixir.FidelityAppWeb.AdminuserLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 09:14:36.305 [error] <0.2281.0> CRASH REPORT Process <0.2281.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"render/1 was not implemented for FidelityAppWeb.AdminuserLive.\n\nMake sure to either explicitly define a render/1 clause with a LiveView template:\n\n    def render(assigns) do\n      ~L\"\"\"\n      ...\n      \"\"\"\n    end\n\nOr create a file at \"/home/sblabreu/projects/fidelity/fidelity/apps/fidelity_app/lib/fidelity_app_web/live/adminuser_live.html.leex\" with the LiveView template.\n">>},[{'Elixir.FidelityAppWeb.AdminuserLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 09:14:36.306 [error] <0.2281.0> Cowboy stream 8 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2228.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"render/1 was not implemented for FidelityAppWeb.AdminuserLive.\n\nMake sure to either explicitly define a render/1 clause with a LiveView template:\n\n    def render(assigns) do\n      ~L\"\"\"\n      ...\n      \"\"\"\n    end\n\nOr create a file at \"/home/sblabreu/projects/fidelity/fidelity/apps/fidelity_app/lib/fidelity_app_web/live/adminuser_live.html.leex\" with the LiveView template.\n">>},[{'Elixir.FidelityAppWeb.AdminuserLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 09:15:04.518 [error] <0.2358.0> CRASH REPORT Process <0.2358.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"render/1 was not implemented for FidelityAppWeb.AdminuserLive.\n\nMake sure to either explicitly define a render/1 clause with a LiveView template:\n\n    def render(assigns) do\n      ~L\"\"\"\n      ...\n      \"\"\"\n    end\n\nOr create a file at \"/home/sblabreu/projects/fidelity/fidelity/apps/fidelity_app/lib/fidelity_app_web/live/adminuser_live.html.leex\" with the LiveView template.\n">>},[{'Elixir.FidelityAppWeb.AdminuserLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 09:15:04.519 [error] <0.2358.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2357.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"render/1 was not implemented for FidelityAppWeb.AdminuserLive.\n\nMake sure to either explicitly define a render/1 clause with a LiveView template:\n\n    def render(assigns) do\n      ~L\"\"\"\n      ...\n      \"\"\"\n    end\n\nOr create a file at \"/home/sblabreu/projects/fidelity/fidelity/apps/fidelity_app/lib/fidelity_app_web/live/adminuser_live.html.leex\" with the LiveView template.\n">>},[{'Elixir.FidelityAppWeb.AdminuserLive',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 09:25:09.215 [error] <0.2840.0> CRASH REPORT Process <0.2840.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => subscribe,kind => nil,module => 'Elixir.Phoenix.PubSub'},[{'Elixir.Phoenix.PubSub',subscribe,['Elixir.FidelityApp.PubSub',nil,[]],[{file,"lib/phoenix/pubsub.ex"},{line,115}]},{'Elixir.FidelityAppWeb.AdminuserLive',mount,3,[{file,"lib/fidelity_app_web/live/adminuser_live.ex"},{line,10}]},{'Elixir.Phoenix.LiveView.Utils','-maybe_call_live_view_mount!/4-fun-0-',4,[{file,"..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 09:25:09.216 [error] <0.2840.0> Cowboy stream 1 with ranch listener 'Elixir.FidelityAppWeb.Endpoint.HTTP' and connection process <0.2838.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => subscribe,kind => nil,module => 'Elixir.Phoenix.PubSub'},[{'Elixir.Phoenix.PubSub',subscribe,['Elixir.FidelityApp.PubSub',nil,[]],[{file,"lib/phoenix/pubsub.ex"},{line,115}]},{'Elixir.FidelityAppWeb.AdminuserLive',mount,3,[{file,"lib/fidelity_app_web/live/adminuser_live.ex"},{line,10}]},{'Elixir.Phoenix.LiveView.Utils','-maybe_call_live_view_mount!/4-fun-0-',4,[{file,"..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-07-09 09:31:29.963 [info] <0.43.0> Application lager started on node nonode@nohost
2020-07-09 09:31:29.980 [info] <0.43.0> Application gen_stage started on node nonode@nohost
2020-07-09 09:31:29.986 [info] <0.43.0> Application broadway started on node nonode@nohost
2020-07-09 09:31:30.005 [info] <0.43.0> Application xmerl started on node nonode@nohost
2020-07-09 09:31:30.038 [info] <0.43.0> Application sasl started on node nonode@nohost
2020-07-09 09:31:30.048 [info] <0.43.0> Application tools started on node nonode@nohost
2020-07-09 09:31:30.053 [info] <0.43.0> Application jsx started on node nonode@nohost
2020-07-09 09:31:30.059 [info] <0.43.0> Application recon started on node nonode@nohost
2020-07-09 09:31:30.093 [info] <0.43.0> Application credentials_obfuscation started on node nonode@nohost
2020-07-09 09:31:30.093 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2020-07-09 09:31:30.105 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2020-07-09 09:31:30.109 [info] <0.43.0> Application amqp started on node nonode@nohost
2020-07-09 09:31:30.109 [info] <0.43.0> Application broadway_rabbitmq started on node nonode@nohost
2020-07-09 09:31:30.174 [info] <0.43.0> Application fidelity_rule_engine started on node nonode@nohost
2020-07-09 09:31:30.200 [info] <0.43.0> Application absinthe started on node nonode@nohost
2020-07-09 09:31:30.213 [info] <0.43.0> Application poison started on node nonode@nohost
2020-07-09 09:31:30.225 [info] <0.43.0> Application argon2_elixir started on node nonode@nohost
2020-07-09 09:31:30.236 [info] <0.43.0> Application absinthe_ecto started on node nonode@nohost
2020-07-09 09:31:30.247 [info] <0.43.0> Application absinthe_error_payload started on node nonode@nohost
2020-07-09 09:31:30.253 [info] <0.43.0> Application absinthe_plug started on node nonode@nohost
2020-07-09 09:31:30.504 [info] <0.43.0> Application jose started on node nonode@nohost
2020-07-09 09:31:30.504 [info] <0.43.0> Application guardian started on node nonode@nohost
2020-07-09 09:31:30.507 [info] <0.43.0> Application guardian_db started on node nonode@nohost
2020-07-09 09:31:30.509 [info] <0.43.0> Application basic_auth started on node nonode@nohost
2020-07-09 09:31:30.516 [info] <0.43.0> Application pow started on node nonode@nohost
2020-07-09 09:31:30.838 [info] <0.43.0> Application mnesia started on node nonode@nohost
2020-07-09 09:31:30.850 [info] <0.43.0> Application gqlgateway started on node nonode@nohost
2020-07-09 09:32:38.532 [error] <0.1101.0>@Elixir.Phoenix.LiveView.Channel:handle_info:134 gen_server <0.1101.0> terminated with reason: call to undefined function 'Elixir.FidelityAppWeb.AdminuserLive':handle_info/2 from 'Elixir.Phoenix.LiveView.Channel':handle_info/2 line 134
2020-07-09 09:32:38.532 [error] <0.1169.0>@Elixir.Phoenix.LiveView.Channel:handle_info:134 gen_server <0.1169.0> terminated with reason: call to undefined function 'Elixir.FidelityAppWeb.AdminuserLive':handle_info/2 from 'Elixir.Phoenix.LiveView.Channel':handle_info/2 line 134
2020-07-09 09:32:38.550 [error] <0.1101.0>@Elixir.FidelityAppWeb.AdminuserLive:handle_info CRASH REPORT Process <0.1101.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.FidelityAppWeb.AdminuserLive':handle_info({'Elixir.FidelityApp.Accounts',[user,created],#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',...},...}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{flash => #{},live_action => nil,...},...})
2020-07-09 09:34:30.096 [error] <0.1292.0>@Elixir.FidelityAppWeb.AdminuserLive:handle_info:70 gen_server <0.1292.0> terminated with reason: no function clause matching 'Elixir.FidelityAppWeb.AdminuserLive':handle_info({'Elixir.FidelityApp.Accounts',[user,created],#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',...},...}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{flash => #{},live_action => nil,...},...}) line 70
2020-07-09 09:34:30.096 [error] <0.1288.0>@Elixir.FidelityAppWeb.AdminuserLive:handle_info:70 gen_server <0.1288.0> terminated with reason: no function clause matching 'Elixir.FidelityAppWeb.AdminuserLive':handle_info({'Elixir.FidelityApp.Accounts',[user,created],#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',...},...}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{flash => #{},live_action => nil,...},...}) line 70
2020-07-09 09:34:30.107 [error] <0.1292.0>@Elixir.FidelityAppWeb.AdminuserLive:handle_info:70 CRASH REPORT Process <0.1292.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.FidelityAppWeb.AdminuserLive':handle_info({'Elixir.FidelityApp.Accounts',[user,created],#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',...},...}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{flash => #{},live_action => nil,...},...}) line 70
