2020-05-03 21:48:04.562 [error] <0.432.0> gen_server <0.432.0> terminated with reason: {socket_error,timeout}
2020-05-03 21:48:04.562 [error] <0.460.0> gen_server <0.460.0> terminated with reason: {socket_error,timeout}
2020-05-03 21:48:04.562 [error] <0.463.0> gen_server <0.463.0> terminated with reason: {socket_error,timeout}
2020-05-03 21:48:04.562 [error] <0.428.0> gen_server <0.428.0> terminated with reason: {socket_error,timeout}
2020-05-03 21:48:04.563 [error] <0.462.0> gen_server <0.462.0> terminated with reason: {socket_error,timeout}
2020-05-03 21:48:04.563 [error] <0.461.0> gen_server <0.461.0> terminated with reason: {socket_error,timeout}
2020-05-03 21:48:04.563 [error] <0.435.0> gen_server <0.435.0> terminated with reason: {socket_error,timeout}
2020-05-03 21:48:04.563 [error] <0.459.0> gen_server <0.459.0> terminated with reason: {socket_error,timeout}
2020-05-03 21:48:04.564 [error] <0.438.0> gen_server <0.438.0> terminated with reason: {socket_error,timeout}
2020-05-03 21:48:04.564 [error] <0.441.0> gen_server <0.441.0> terminated with reason: {socket_error,timeout}
2020-05-03 21:48:04.566 [error] <0.432.0> CRASH REPORT Process <0.432.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-05-03 21:48:04.566 [error] <0.438.0> CRASH REPORT Process <0.438.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-05-03 21:48:04.567 [error] <0.435.0> CRASH REPORT Process <0.435.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-05-03 21:48:04.567 [error] <0.428.0> CRASH REPORT Process <0.428.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-05-03 21:48:04.568 [error] <0.430.0> Supervisor {<0.430.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.431.0>, {amqp_params_network,<<"guest">>,<<"WXbiYoxjNQsnjd4ZoauYGc4O3FX3KPAu9H7as3jStJB+pBMveI4Fv9O1ijDTm2...">>,...}) at <0.432.0> exit with reason {socket_error,timeout} in context child_terminated
2020-05-03 21:48:04.568 [error] <0.430.0> Supervisor {<0.430.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.431.0>, {amqp_params_network,<<"guest">>,<<"WXbiYoxjNQsnjd4ZoauYGc4O3FX3KPAu9H7as3jStJB+pBMveI4Fv9O1ijDTm2...">>,...}) at <0.432.0> exit with reason reached_max_restart_intensity in context shutdown
2020-05-03 21:48:04.569 [error] <0.433.0> Supervisor {<0.433.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.434.0>, {amqp_params_network,<<"guest">>,<<"3OX+VbgKjbZy34/i6XEVvcDvpEwHD4rioXGBSO8MN0s8x/e8iNRNdFtKlxTUTf...">>,...}) at <0.435.0> exit with reason {socket_error,timeout} in context child_terminated
2020-05-03 21:48:04.569 [error] <0.441.0> CRASH REPORT Process <0.441.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-05-03 21:48:04.570 [error] <0.433.0> Supervisor {<0.433.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.434.0>, {amqp_params_network,<<"guest">>,<<"3OX+VbgKjbZy34/i6XEVvcDvpEwHD4rioXGBSO8MN0s8x/e8iNRNdFtKlxTUTf...">>,...}) at <0.435.0> exit with reason reached_max_restart_intensity in context shutdown
2020-05-03 21:48:04.571 [error] <0.439.0> Supervisor {<0.439.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.440.0>, {amqp_params_network,<<"guest">>,<<"ZdUFJn+7a+0IQsyBglUbFmQe0NdL3AlRKOCzj23LnjTikDmhLgzBc8roWL4i4i...">>,...}) at <0.441.0> exit with reason {socket_error,timeout} in context child_terminated
2020-05-03 21:48:04.571 [error] <0.424.0> Supervisor {<0.424.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.427.0>, {amqp_params_network,<<"guest">>,<<"Ws9MTE8zmFKDPlfYxxfl2rauC5tfVWUnJwS4GYXRQm7f9gVzO1UhAFH1nDgwPV...">>,...}) at <0.428.0> exit with reason {socket_error,timeout} in context child_terminated
2020-05-03 21:48:04.572 [error] <0.436.0> Supervisor {<0.436.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.437.0>, {amqp_params_network,<<"guest">>,<<"CSmf1buCokUep23isY48LLAL4c7sW1A1ksWhayvNATAejQKvyWJkVt6Unyr2lo...">>,...}) at <0.438.0> exit with reason {socket_error,timeout} in context child_terminated
2020-05-03 21:48:04.572 [error] <0.439.0> Supervisor {<0.439.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.440.0>, {amqp_params_network,<<"guest">>,<<"ZdUFJn+7a+0IQsyBglUbFmQe0NdL3AlRKOCzj23LnjTikDmhLgzBc8roWL4i4i...">>,...}) at <0.441.0> exit with reason reached_max_restart_intensity in context shutdown
2020-05-03 21:48:04.573 [error] <0.424.0> Supervisor {<0.424.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.427.0>, {amqp_params_network,<<"guest">>,<<"Ws9MTE8zmFKDPlfYxxfl2rauC5tfVWUnJwS4GYXRQm7f9gVzO1UhAFH1nDgwPV...">>,...}) at <0.428.0> exit with reason reached_max_restart_intensity in context shutdown
2020-05-03 21:48:04.574 [error] <0.436.0> Supervisor {<0.436.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.437.0>, {amqp_params_network,<<"guest">>,<<"CSmf1buCokUep23isY48LLAL4c7sW1A1ksWhayvNATAejQKvyWJkVt6Unyr2lo...">>,...}) at <0.438.0> exit with reason reached_max_restart_intensity in context shutdown
2020-05-03 22:51:01.424 [error] <0.586.0> gen_server <0.586.0> terminated with reason: {socket_error,timeout}
2020-05-03 22:51:01.424 [error] <0.589.0> gen_server <0.589.0> terminated with reason: {socket_error,timeout}
2020-05-03 22:51:01.424 [error] <0.585.0> gen_server <0.585.0> terminated with reason: {socket_error,timeout}
2020-05-03 22:51:01.424 [error] <0.560.0> gen_server <0.560.0> terminated with reason: {socket_error,timeout}
2020-05-03 22:51:01.425 [error] <0.587.0> gen_server <0.587.0> terminated with reason: {socket_error,timeout}
2020-05-03 22:51:01.425 [error] <0.589.0> CRASH REPORT Process <0.589.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-05-03 22:51:01.425 [error] <0.588.0> gen_server <0.588.0> terminated with reason: {socket_error,timeout}
2020-05-03 22:51:01.426 [error] <0.586.0> CRASH REPORT Process <0.586.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-05-03 22:51:01.426 [error] <0.585.0> CRASH REPORT Process <0.585.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-05-03 22:51:01.426 [error] <0.566.0> gen_server <0.566.0> terminated with reason: socket_closed_unexpectedly
2020-05-03 22:51:01.427 [error] <0.562.0> Supervisor {<0.562.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.12>, <0.563.0>, <0.575.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 192.168.1.73:40325 -> 192.168.1.64:32771">>) at <0.586.0> exit with reason {socket_error,timeout} in context child_terminated
2020-05-03 22:51:01.427 [error] <0.587.0> CRASH REPORT Process <0.587.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-05-03 22:51:01.427 [error] <0.563.0> gen_server <0.563.0> terminated with reason: {socket_error,timeout}
2020-05-03 22:51:01.428 [error] <0.562.0> Supervisor {<0.562.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.12>, <0.563.0>, <0.575.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 192.168.1.73:40325 -> 192.168.1.64:32771">>) at <0.586.0> exit with reason reached_max_restart_intensity in context shutdown
2020-05-03 22:51:01.429 [error] <0.557.0> gen_server <0.557.0> terminated with reason: {socket_error,timeout}
2020-05-03 22:51:01.430 [error] <0.559.0> Supervisor {<0.559.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.14>, <0.560.0>, <0.579.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 192.168.1.73:41503 -> 192.168.1.64:32771">>) at <0.589.0> exit with reason {socket_error,timeout} in context child_terminated
2020-05-03 22:51:01.430 [error] <0.588.0> CRASH REPORT Process <0.588.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-05-03 22:51:01.430 [error] <0.559.0> Supervisor {<0.559.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.14>, <0.560.0>, <0.579.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 192.168.1.73:41503 -> 192.168.1.64:32771">>) at <0.589.0> exit with reason reached_max_restart_intensity in context shutdown
2020-05-03 22:51:01.431 [error] <0.565.0> Supervisor {<0.565.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.13>, <0.566.0>, <0.576.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 192.168.1.73:49675 -> 192.168.1.64:32771">>) at <0.587.0> exit with reason {socket_error,timeout} in context child_terminated
2020-05-03 22:51:01.432 [error] <0.565.0> Supervisor {<0.565.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.13>, <0.566.0>, <0.576.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 192.168.1.73:49675 -> 192.168.1.64:32771">>) at <0.587.0> exit with reason reached_max_restart_intensity in context shutdown
2020-05-03 22:51:01.432 [error] <0.556.0> Supervisor {<0.556.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.15>, <0.557.0>, <0.577.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 192.168.1.73:47097 -> 192.168.1.64:32771">>) at <0.588.0> exit with reason {socket_error,timeout} in context child_terminated
2020-05-03 22:51:01.433 [error] <0.556.0> Supervisor {<0.556.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.15>, <0.557.0>, <0.577.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 192.168.1.73:47097 -> 192.168.1.64:32771">>) at <0.588.0> exit with reason reached_max_restart_intensity in context shutdown
2020-05-03 22:51:01.434 [error] <0.569.0> gen_server <0.569.0> terminated with reason: {socket_error,timeout}
2020-05-03 22:51:01.435 [error] <0.568.0> Supervisor {<0.568.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.16>, <0.569.0>, <0.578.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 192.168.1.73:53547 -> 192.168.1.64:32771">>) at <0.585.0> exit with reason {socket_error,timeout} in context child_terminated
2020-05-03 22:51:01.435 [error] <0.568.0> Supervisor {<0.568.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.16>, <0.569.0>, <0.578.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 192.168.1.73:53547 -> 192.168.1.64:32771">>) at <0.585.0> exit with reason reached_max_restart_intensity in context shutdown
2020-05-03 22:51:01.436 [error] <0.566.0> CRASH REPORT Process <0.566.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 751
2020-05-03 22:51:01.436 [error] <0.560.0> CRASH REPORT Process <0.560.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-05-03 22:51:01.437 [error] <0.564.0> Supervisor {<0.564.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.565.0>, {amqp_params_network,<<"guest">>,<<"9DHkNif3RAHUjblFV6yscTuHd7vNQ/1NbKAzCIqPHL0FmFVAf7FNRQn0Sah6nV...">>,...}) at <0.566.0> exit with reason socket_closed_unexpectedly in context child_terminated
2020-05-03 22:51:01.437 [error] <0.564.0> Supervisor {<0.564.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.565.0>, {amqp_params_network,<<"guest">>,<<"9DHkNif3RAHUjblFV6yscTuHd7vNQ/1NbKAzCIqPHL0FmFVAf7FNRQn0Sah6nV...">>,...}) at <0.566.0> exit with reason reached_max_restart_intensity in context shutdown
2020-05-03 22:51:01.438 [error] <0.558.0> Supervisor {<0.558.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.559.0>, {amqp_params_network,<<"guest">>,<<"E+KVjD/a67Gvw6LRyd7oLsN8kGxUE/z6hDshyxhf786+KrjHfW/i6KL0HS7LcX...">>,...}) at <0.560.0> exit with reason {socket_error,timeout} in context child_terminated
2020-05-03 22:51:01.438 [error] <0.557.0> CRASH REPORT Process <0.557.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-05-03 22:51:01.439 [error] <0.558.0> Supervisor {<0.558.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.559.0>, {amqp_params_network,<<"guest">>,<<"E+KVjD/a67Gvw6LRyd7oLsN8kGxUE/z6hDshyxhf786+KrjHfW/i6KL0HS7LcX...">>,...}) at <0.560.0> exit with reason reached_max_restart_intensity in context shutdown
2020-05-03 22:51:01.439 [error] <0.555.0> Supervisor {<0.555.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.556.0>, {amqp_params_network,<<"guest">>,<<"8Gu9gjdGcHuHcp4aAQ+3lqxNXJNutGd5AUunbfH9Wr8/5X/99EFjpBSXTF3V+Q...">>,...}) at <0.557.0> exit with reason {socket_error,timeout} in context child_terminated
2020-05-03 22:51:01.440 [error] <0.555.0> Supervisor {<0.555.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.556.0>, {amqp_params_network,<<"guest">>,<<"8Gu9gjdGcHuHcp4aAQ+3lqxNXJNutGd5AUunbfH9Wr8/5X/99EFjpBSXTF3V+Q...">>,...}) at <0.557.0> exit with reason reached_max_restart_intensity in context shutdown
2020-05-03 22:51:01.440 [error] <0.563.0> CRASH REPORT Process <0.563.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-05-03 22:51:01.440 [error] <0.569.0> CRASH REPORT Process <0.569.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-05-03 22:51:01.441 [error] <0.561.0> Supervisor {<0.561.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.562.0>, {amqp_params_network,<<"guest">>,<<"LBpfNCbyP9bAQKYnXlWDHVXHM1cmc0TX6GzQQfD6FT3cNCDd8MS+BBUH9HbZMi...">>,...}) at <0.563.0> exit with reason {socket_error,timeout} in context child_terminated
2020-05-03 22:51:01.441 [error] <0.561.0> Supervisor {<0.561.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.562.0>, {amqp_params_network,<<"guest">>,<<"LBpfNCbyP9bAQKYnXlWDHVXHM1cmc0TX6GzQQfD6FT3cNCDd8MS+BBUH9HbZMi...">>,...}) at <0.563.0> exit with reason reached_max_restart_intensity in context shutdown
2020-05-03 22:51:01.442 [error] <0.567.0> Supervisor {<0.567.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.568.0>, {amqp_params_network,<<"guest">>,<<"Tvvo2DcezHo+NdTUtyFRdmFAipdYBLk/PNx/KNseMPn0X6FalysKDSJiDjJkih...">>,...}) at <0.569.0> exit with reason {socket_error,timeout} in context child_terminated
2020-05-03 22:51:01.442 [error] <0.567.0> Supervisor {<0.567.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.568.0>, {amqp_params_network,<<"guest">>,<<"Tvvo2DcezHo+NdTUtyFRdmFAipdYBLk/PNx/KNseMPn0X6FalysKDSJiDjJkih...">>,...}) at <0.569.0> exit with reason reached_max_restart_intensity in context shutdown
